import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { ReactElement } from 'react'
import styles from '../styles/Home.module.css'

interface inputProps  {
  label: string
  inputRef: any
}

const Home: NextPage = () => {

  const washingTimeInputRef = React.useRef<HTMLInputElement>(null);
  const endOfWasing = React.useRef<HTMLInputElement>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>Washing Time Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.row}>
          <Input inputRef={washingTimeInputRef} label={'Washing time'}/>
          <Input inputRef={washingTimeInputRef} label={'End of washing'}/>
        </div>
      </main>
    </div>
  )
}

function Input({label, inputRef}: inputProps): ReactElement{
  
  return (
    <div className={styles.input}>
      <label>{label}</label>
      <input ref={inputRef}/>
    </div>
  )
}

export default Home
